### ISSUE TITLE
pictureStyle and pictureClassName on SRCImage component

### ISSUE THREAD

**Issue by dovca** [datocms/react-datocms#101]
Why are there `pictureStyle` and `pictureClassName` props on the `<Image>` component, but not on `<SRCImage>`? Can you please add them?

**Comment by stefanoverna** [comment]
With `<SRCImage />` you can simply use `className` and `style` to achieve the same result!

**Comment by dovca** [comment]
Hi Stefano, thanks for the blazing fast reply. Unfortunately I can't, because those props are applied on the `<img>` element, not `<picture>`.

In my use case, I have a bunch of `<SRCImage>`s as direct children of a flex container. I need to specify some inline styles concerning `flex-grow` to the `<picture>`, but I see the `style` prop applied to the nested `<img>` element, which isn't doing the right job. I can work around this with an additional `<div>` wrapper around `<SRCImage>`, but I feel that should not be required.

**Comment by stefanoverna** [comment]
Both `<Image>` and `<SRCImage>` do not allow you to currently set a className for the `<picture>` tag. The `pictureStyle` and `pictureClassName` props are set on the `<img />`.

https://github.com/datocms/react-datocms/blob/8811da7e2df525a626d8f31ed99198ee6e623d4c/src/Image/index.tsx#L276

We need to think about how we can solve this problem.

**Comment by dovca** [comment]
Ah, I see. I got confused by the docs then, sorry.

### `<SRCImage>`
- `className` binds to nested `<img>`

### `<Image>`
- `className` binds to root `<div>` node
- `pictureClassName` binds to nested `<img>`

This means that there is currently no way to bind `className` to root node of `<SRCImage>` and the props of `<Image>` are named rathe confusingly.

**Comment by stefanoverna** [comment]
Alright, we decided to release a major new version, and rename the props:

https://github.com/datocms/react-datocms/releases/tag/v7.0.0
https://github.com/datocms/react-datocms/releases/tag/v7.0.1
