### ISSUE TITLE
Remix new route, see old Image for a moments

### ISSUE THREAD

**Issue by eliawk** [datocms/react-datocms#102]
Hello,
I've just created a new application using Remix.js. 
When I navigate through a different route of the same Entity for some moments I still see the old cover Image, then the new one appears. Same behavior if I use **priority**.
I'm using you Image component like this:
```
<Image
  data={image}
  objectFit="cover"
  layout="fill"
  objectPosition="center"
/>
```

any ideas?

tx

**Comment by arcataroger** [comment]
Hi @eliawk,

Could you please provide a reproducible example?

**Comment by eliawk** [comment]
Hey @arcataroger here you can see the issues:
https://develop.cinemambiente.media/en/movies/dark-waters

To reproduce the issue scroll down and click on a related movie. On the new page the content updates and after a short delay the cover image update too.

thanks for looking at!

**Comment by arcataroger** [comment]
@eliawk Can you please provide the code for that page? You can post a snippet here, or share the repo with me at @arcataroger

**Comment by eliawk** [comment]
@arcataroger I've add youto the repo, but I think I've fixed it 
adding a **key** to to the `<Image>` component like this:
```
<Image
  key={id}
  data={image}
  objectFit="cover"
  layout="fill"
  objectPosition="center"
  placeholderClassName="!h-full !top-0 !left-0"
/>
```
to force the redraw of the component, is there another better way to achieve the same result?

**Comment by stefanoverna** [comment]
Yes, we probably need to implement the same solution internally ourselves using `key`. Thank you for the report, we will try to release a new version soon!

**Comment by stefanoverna** [comment]
In fact, I discovered that this is exactly the behavior of an `<img />` tag when its `src` changes, as well as the Image component of Next. So I decided not to handle this case but to document its solution in the README.

https://github.com/datocms/react-datocms/blob/master/docs/image.md#changing-data
