### ISSUE TITLE
Next.js + Live Preview error using `getStaticProps` and `useQuerySubscription`

### ISSUE THREAD

**Issue by tundera** [datocms/react-datocms#19]
Hey I'm getting this error when I try to set up the `useQuerySubscription` hook in a Next.js project built with TypeScript. It seems to be happening because the `subscription` prop is undefined, or some nested value within is undefined, but I don't know why. Doesn't seem debuggable either 😢...here's the error message I'm getting when I try to hit the `/blog/[slug].tsx` page in preview mode:

<img width="1086" alt="Screen Shot 2021-01-18 at 9 17 01 PM" src="https://user-images.githubusercontent.com/61833561/104987301-9acc0c00-59d2-11eb-85a4-eb01c444e7c3.png">

I added a nice preview/published toggle up top to make it easy to test out. Here's the [repo](https://github.com/tundera/next-goat/tree/feature/add-datocms-integration) on my working branch if it's helpful. The page I'm trying to hit is in `src/pages/blog/[slug].tsx`. I tried to add a live preview subscription to the page at `src/pages/blog/index.tsx` too, just to make sure it's not specific to pages generated from `getStaticPaths`. Same issue happened there with a similar error:

<img width="1049" alt="Screen Shot 2021-01-18 at 9 17 24 PM" src="https://user-images.githubusercontent.com/61833561/104987334-acadaf00-59d2-11eb-82c3-6ba8a3f80031.png">

I like the CMS and it's been fun to work with, but I was hoping to use the live preview feature for blog stuff. Hopefully someone else will have an idea here 😄

**Comment by stefanoverna** [comment]
Hey @tundera sorry for the delay! Did you happen to delete the repo?

**Comment by stefanoverna** [comment]
Seems to me that you were using a `gql` query.. something like this:

```js
export async function getStaticProps() {
  const graphqlRequest = {
    query: gql`YOUR QUERY HERE`,
    variables: { limit: 10 },
  };
  return {
    props: {
      subscription: {
        ...graphqlRequest,
        initialData: await request(graphqlRequest),
        token: process.env.NEXT_PUBLIC_DATOCMS_API_TOKEN,
      },
    },
  };
}
```

`gql` is not serializable into JSON, so you should convert it to string before passing it down as a prop to `getStaticProps`!

I'm gonna close this for now, feel free to reopen if needed ok?
