### ISSUE TITLE
API sends wrong height and aspectRatio after transform

### ISSUE THREAD

**Issue by dbismut** [datocms/react-datocms#2]
Hey, this might be an API bug but I thought I would report it here:

I'm querying an image with the following transforms:

```graphql
cover {
  responsiveImage(imgixParams: { fit: crop, w: 900, h: 1280 }) {
    ...ResponsiveImageFragment
  }
}
```

The response from the API gives be the following object:

![image](https://user-images.githubusercontent.com/5003380/76712918-32126400-671d-11ea-9618-b78750f095fd.png)

Notice the height which is `639` when it should be `1280`. Aspect ratio is therefore also wrong.

The src is correctly transformed by imgix:

https://www.datocms-assets.com/20125/1580675830-gabriel-style.jpg?fit=crop&h=1280&w=900

PS: just noticed that `height` is missing in the Readme file as part of the `responsiveImage` attributes table.

**Comment by matjack1** [comment]
hey @dbismut but the original image width is 639 so we are returning that as that's the maximum you can get? Does that makes sense?

**Comment by dbismut** [comment]
Hm no it doesn't make sense since the image returned by imgix has a height of `900`. The docs say height and width are post transform. The problem with this is that you're returning the correct width and the wrong height and wrong aspect ratio.

That makes react-datocms interpret the image like so:

![image](https://user-images.githubusercontent.com/5003380/76748527-31a8b600-677b-11ea-8ac5-815ba4183a77.png)

When it should be:

![image](https://user-images.githubusercontent.com/5003380/76748561-46854980-677b-11ea-9826-ca7ae85940d5.png)

The way I found to correct this is to manually set the height like so:

```jsx
<Image data={{ ...cover.responsiveImage, height: 1280 }} />
```

But this is not ideal.

**Comment by matjack1** [comment]
Makes sense, let me check what we should do here

**Comment by stefanoverna** [comment]
Thanks @dbismut, we have fixed this! :)
