### ISSUE TITLE
[FEATURE] Allow ability to provide alt manually

### ISSUE THREAD

**Issue by julienben** [datocms/react-datocms#23]
Hey there!

In some images, we don't require the `alt` attribute to be added to the image in Dato. Instead, we want to provide it from a different field.

I'll give you an example: We have a list of employees on our site. The `alt` can simply be the name of the employee, we don't want to duplicate the name in the `alt` field for each image.

In order to "hack" it, we do this:

```js
return <Image data={{ ...data, alt }} {...otherProps} />;
```

Would it make sense to allow doing this instead?

```js
return <Image data={{ data }} alt={alt} {...otherProps} />;
```

If an `alt` is provided, the component would take that one. Otherwise, it would look for it in the `data`.

(The second example seemed so intuitive to me that I originally wrote it that way without realizing that it wasn't taking the `alt` from the prop. 😅)

WDYT?

**Comment by stefanoverna** [comment]
Hi! Your current solution seems totally fine! Having two places where you can specify `alt` seems even more confusing to me (not immediately clear how the two interact) 😕
