### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by bramvdpluijm** [datocms/react-datocms#27]
Currently react-datocms doesn't seem to support Webpack 5. 

## Process:

1. Enable webpack 5
2. Import Image module (import { Image } from "react-datocms";)

## Expected result:
react-datocms should support webpack5 in order to be future proof

## Current result:
When enabling webpack 5 and importing the Image module from react-datocms package, an error is thrown `ReferenceError: module is not defined`.

![image](https://user-images.githubusercontent.com/9077223/115211192-9f05e380-a0ff-11eb-906a-8f7c45882de7.png)

**Comment by stefanoverna** [comment]
Are you using Next.js? Which version of react-datocms and next packages do you have?

**Comment by stefanoverna** [comment]
Just tested our Next.js demo with webpack 5 enabled, and everything works.

https://www.datocms.com/marketplace/starters/nextjs-blog

I'm going to close this, but I'll follow the issue, so if you have more info feel free to share them here!
