### ISSUE TITLE
Package is not tree-shakeable. Need to use exact import or the entire package will be bundled.

### ISSUE THREAD

**Issue by wildpow** [datocms/react-datocms#28]
It's a bit above my head to know if a project is tree-shakeable or not, so I turn to Bundlephobia for this assurance. Not sure how accurate this feature is, but this package is listed as being not tree-shakeable [here](https://bundlephobia.com/result?p=react-datocms@1.6.0). Is this incorrect, or should I be using a different method to determine if a project is indeed tree-shakeable?

**Comment by wildpow** [comment]
Well, I believe I answered my question. Using the import suggested in the docs adds 26.8Kb to a production bundle.

### Using the import `import { StructuredText } from "react-datocms";`
![Screen Shot 2021-04-23 at 2 33 41 PM](https://user-images.githubusercontent.com/17464319/115931974-ef9f7880-a440-11eb-9710-cc48f1c4e982.png)
----------
### Using the import `import { StructuredText } from "react-datocms/dist/StructuredText";`

![Screen Shot 2021-04-23 at 2 35 01 PM](https://user-images.githubusercontent.com/17464319/115932099-1b226300-a441-11eb-8030-6e9abb010aca.png)

**Comment by stefanoverna** [comment]
Hey, v1.6.3 should be tree-shakable, at least from my experiments!
