### ISSUE TITLE
Issue with transparent images

### ISSUE THREAD

**Issue by cj** [datocms/react-datocms#3]
The placeholder image (base64) still shows behind a transparent image.  A solution might be to set display none once loaded.

https://share.getcloudapp.com/RBudkbQq

**Comment by cj** [comment]
Actually if you add a css transition to the placeholder and then add a `visibility: hidden;` it works really well.

This patch works great for now https://gist.github.com/cj/462331ac9c132b6c5fe23042425c44c6

(I use tailwind).

**Comment by stefanoverna** [comment]
Fixed in last version!
