### ISSUE TITLE
Consider removing IntersectionObserver from bundle

### ISSUE THREAD

**Issue by thebuilder** [datocms/react-datocms#31]
I understand the `intersection-observer` polyfill was added to the package in #6, which does fix the issue on old browsers.
But, would it better to inform users about how to include the polyfill if older browsers needs to be supported? Since iOS 12.2 (March 2019) it's supported natively in all modern browsers: https://caniuse.com/intersectionobserver

Right now the `intersection-observer` polyfill is accounting for 25% of your package size:
https://bundlephobia.com/result?p=react-datocms@1.6.3

Since you only use the hook for lazy loading images, an option would could be to simply disable the `useInView` hook if the `IntersectionObserver` isn't found. This would have the treat images as normal, without lazy loading support.

Also seems like you are already checking if the `IntersectionObserver` exists? Wouldn't this always be `true`, since you import the polyfill?
https://github.com/datocms/react-datocms/blob/master/src/Image/index.tsx#L10-L12

Keep in mind the `isIntersectionObserverAvailable` check will cause a hydration error if it isn't available, since you add the `src` during the rehydration phase on the client. Could cause a potential mismatch, e.g. no `src` being added to the HTML.
https://github.com/datocms/react-datocms/blob/master/src/Image/index.tsx#L79-L83.

**Comment by thebuilder** [comment]
You could also combine the `IntersectionObserver` check, with a check for `loading="lazy"` support - if the browser supports native lazy loading, you could skip creating the observer, and defer the work directly to the `<img>`.

See https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#lazy-image-load for how this can be accomplished.

**Comment by stefanoverna** [comment]
Done in 3.0.0!
