### ISSUE TITLE
Default renders from StructuredText can not be styled with styled-jsx

### ISSUE THREAD

**Issue by wjeliot** [datocms/react-datocms#32]
I have a Structured Text field in my record. Inside it, there is some text in p, h2, blockquote, and h3 tags. There is also a block inside of which I have a 'Multi-paragraph text' field. So, the schema looks like this:

> Record
>> Structured Text
>>> p
>>> h2
>>> blockquote
>>> h3
>>> Block
>>>> Multi-paragraph text
>>>>> Markdown paragraph (becomes a <p> tag through API)

Every part of the HTML returned by the <StructuredText> React component can be styled with global, standard CSS. And when I use the `customRules` prop to provide my own renderers – such as a rule that converts h3 tags to anchor links – then that custom returned html can be styled with styled-jsx.

However, I find that I'm unable to style HTML elements which do not have a custom renderer attached. So for example, my p and blockquote tags, which are handled by the <StructuredText> component natively, do not pick up the CSS defined in my styled-jsx. This can be confirmed when I inspect the HTML in my browser.

The elements whose rendering I decided (like the h3 tags) have a class attribute and the correct styles applied. The elements which <StructuredText> handles itself do not pick up my styles; it's as if they are sanitised before being inserted into the DOM, or perhaps they don't encounter my styled-jsx at any point in the cycle.

```html
<div>
  <StructuredText data={record.content} /> // customRules omitted for clarity
  <style jsx>{`
    p {
      color: orange;
    }
  `}</style>
</div>
```

The high-level paragraph does not become orange. However, the paragraph inside the 'Multi-paragraph text' field does become orange!

I know I can fix this using another custom render rule, but I would prefer not to do that if possible. Is this a limitation of the way styled-jsx applies its styles to the HTML? Or an bug in the way <StructuredText> renders elements by default? Cookies in advance for any help or advice 🍪

**Comment by stefanoverna** [comment]
Hey! Take a look at styled-jsx README, this is actually a "feature" of styled-jsx:

![Screenshot 2021-06-10 at 10 25 23](https://user-images.githubusercontent.com/51573/121491394-31c35000-c9d6-11eb-88a2-1a94141d37c9.png)

Styles are applied only to tags directly rendered by the component itself. [Following their guide](https://github.com/vercel/styled-jsx#styling-third-parties--child-components-from-the-parent), you need to do this to make it work:

```
<div className="post">
  <StructuredText data={record.content} />
  <style jsx>{`
    .post > :global(p) {
      color: orange;
    }
  `}</style>
</div>
```
