### ISSUE TITLE
<Image> component doesn't know how to handle SVGs

### ISSUE THREAD

**Issue by arcataroger** [datocms/react-datocms#35]
SVG files, which can be selected in the asset picker in DatoCMS, break the <Image> component because they don't have `responsiveImage` data in the GraphQL API. It's fine if [Imgix transformations can't be applied to SVG files](https://community.datocms.com/t/imgix-enable-svg-as-input-format/1743), but could the React component at least pass through the SVG file and let the browser handle rendering? 

Otherwise,  using the <Image> component will result in fatal errors without explicit checks for SVGs. That, or maybe the field validation could have a "Raster Images" only type that doesn't include SVGs, so editors can't accidentally select them?

**Comment by matjack1** [comment]
Yes @arcataroger I agree with you! We should handle SVGs without breaking. I'll add this to our backlog

**Comment by arcataroger** [comment]
Great, thank you!

**Comment by stefanoverna** [comment]
My 2c:

* We cannot render a fallback native `<img>` for SVG files as `.responsiveImage` is `null`, so we don't have any information via props to use as `src` attribute for the tag.
* Changing behaviour for SVG files might be surprising and would require new styling props to handle the case.
* Silently swallowing the error an rendering nothing might be an option, but I'm not sure if it's better than the current situation.
* You can already add a custom "extension" validation with the file formats you prefer. Having a "raster images" validation would make things a little bit easier.

**Comment by arcataroger** [comment]
Stefano brings up good points. Adding more complexity to support SVGs would probably result in more confusion and bugs later, especially since it's handled differently by different browsers and frameworks.

Probably just adding a default "raster images" validation would make this simpler while still preventing breakage?

**Comment by stefanoverna** [comment]
Closing the issue from this side!
