### ISSUE TITLE
[Image component] What's the best strategy to fill parent?

### ISSUE THREAD

**Issue by dbismut** [datocms/react-datocms#42]
Hi again, what would be the best strategy to fill a parent?
Something like `next/image` `layout="fill"` prop?

**Comment by stefanoverna** [comment]
I'm thinking about adding the same `layout` prop: https://github.com/datocms/react-datocms/pull/43

Any thought?

**Comment by stefanoverna** [comment]
This would be a breaking change, so we should bump a major version

**Comment by dbismut** [comment]
Indeed... But I agree this would be the perfect solution.

**Comment by stefanoverna** [comment]
Done, released as 2.0.1!
