### ISSUE TITLE
Update to latest datocms-structured-text-utils

### ISSUE THREAD

**Issue by JanStevens** [datocms/react-datocms#46]
Hi 👋 ,

When implementing `customNodeRules` I noticed that the type guards didn't work because `react-datocms` pulls in `datocms-structured-text-utils` v1 while the latest version is v2.

Can this package be updated to use v2 or at least update the readme to install `datocms-structured-text-utils` v1, the type guards are not compatible between v1 and v2.

Regards,

**Comment by stefanoverna** [comment]
Done in 3.0.1!
