### ISSUE TITLE
Image placeholders a11y errors

### ISSUE THREAD

**Issue by mzampetti** [datocms/react-datocms#48]
Image placeholders use role=presentation attribute, and are marked as error by a11y verification tools.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role

"The presentation role is used to remove semantic meaning from an element and any of its related child elements", but the element remains present in the accessibility tree.

The aria-hidden attribute should be the best solution for placeholder, not affecting the UI, and removing them from the accessibility tree.

**Comment by stefanoverna** [comment]
Makes sense!

**Comment by stefanoverna** [comment]
Fixed in v3.0.3!
