### ISSUE TITLE
Image placeholders and lighthouse report

### ISSUE THREAD

**Issue by mzampetti** [datocms/react-datocms#49]
Placeholder images are marked as errors in Lighthouse report Best Practices / User Experience

![Screenshot 2022-02-02 at 12 55 43](https://user-images.githubusercontent.com/1792077/152150641-c3a25f8a-a33b-475e-ad36-c7d4f26e93f9.png)

**Comment by stefanoverna** [comment]
Placeholders are so small that rounding errors are inevitable.. The correct aspect ratio in the first case is 0.76, but the placeholder should be 18.24px x 24, which is not possible :/

An alternative would be to use a div instead of an <img /> tag. Thoughts?

**Comment by stefanoverna** [comment]
Solved v3.0.3, by only resizing the placeholder using `width: 100%` (`height: 100%` is now dropped), and ensuring that server-side thumbs are always generated with aspect ratio <= than the original image.
