### ISSUE TITLE
Can't pass children to component to use as a background image

### ISSUE THREAD

**Issue by e-karma** [datocms/react-datocms#5]
Looking at the output CSS, it creates a background-image several nested divs in, but you can't pass nested children through it.  Enabling an image-background component with text / CTA's over it would be incredibly helpful!  Thanks for your work otherwise.  Keep up the good work!

**Comment by matjack1** [comment]
thank you for the suggestion! We've noted that down for future developments

**Comment by stefanoverna** [comment]
Take a look at the new option `layout="fill"`, should be helpful to solve your use case!

```
<div style={{ position: 'relative' }}>
  <Image layout="fill" data={..} />
  <div>
     Your text/buttons/CTA can be placed here!
  </div>
</div>
```

https://github.com/datocms/react-datocms#layout-mode
