### ISSUE TITLE
`Invalid character` error in `universal-base64` dependency.

### ISSUE THREAD

**Issue by metart43** [datocms/react-datocms#53]
@stefanoverna swtiching to [universal-base64](https://www.npmjs.com/package/universal-base64) lib lin [v3.0.2](https://github.com/datocms/react-datocms/compare/v3.0.1...v3.0.2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R82) started causing issues on Windows based OS. Specififcaly for IE and Firefox browsers.

I get `Invalid character` error in `node_modules/universal-base64/dist/browser.js:11:12`

I know this might not be super helpful but below is a screenshot from Sentry.

<img width="1558" alt="Screenshot 2022-02-23 at 16 13 58" src="https://user-images.githubusercontent.com/27081787/155360049-eebc13db-7301-430f-ae86-53efdda4da62.png">

**Comment by stefanoverna** [comment]
Are you able to reproduce it yourself @metart43? Can you give us the URL of a page reproducing the issue? Thanks!

**Comment by matjack1** [comment]
hey @metart43 I've tried this example: https://github.com/datocms/react-datocms/tree/master/examples/images-and-seo/vanilla-react on Windows with Firefox, but everything works fine. Can you reproduce on the example?

**Comment by metart43** [comment]
I will close the issue for right now due to the fact that I won' be able to reproduce it at the moment. I simply do not have acess to Windows based OS device.
