### ISSUE TITLE
Inconsistent rendering for special nodes in StructuredText

### ISSUE THREAD

**Issue by kamodulin** [datocms/react-datocms#55]
Hello,

I'm running into an issue where blocks are not rendering properly when they follow inline records and record links.

Here is an example implementation with debugging render functions:
```typescript
<StructuredText
  data={data}
  renderBlock={({ record }: { record: Block }) => {
    switch (record.__typename) {
      case "ImageRecord":
        return <div className="text-blue-500">Image</div>;
      case "PersonInvolvedRecord":
        return <div className="text-yellow-500">PersonInvolved</div>;
      default:
        return null;
    }
  }}
  renderInlineRecord={({ record }: { record: Record }) => {
    switch (record.__typename) {
      case "ArticleRecord":
        return <div className="bg-pink-200">ArticleInline</div>;
      case "GuideRecord":
        return <div className="bg-green-200">GuideInline</div>;
      default:
        return null;
    }
  }}
  renderLinkToRecord={({
    record,
    children,
  }: {
    record: Record,
    children: any,
  }) => {
    switch (record.__typename) {
      case "ArticleRecord":
        return <div className="border border-indigo-400">ArticleLink</div>;
      case "GuideRecord":
        return <div className="border border-green-400">GuideLink</div>;
      default:
        return null;
    }
  }}
/>;

```

Here is a side-by-side comparison of what I expect and what the nodes actually look like:

Expectation            |  Actual output
-------------------------|-------------------------
<img src="https://user-images.githubusercontent.com/21014252/159615158-d03faac7-a56e-46c0-890d-daa0e6002b35.png" alt="correct" height="720"/>  |  <img src="https://user-images.githubusercontent.com/21014252/159615256-53999b30-dc3c-43aa-91e1-dab9a46cf852.png" alt="incorrect" height="720"/> 

As you can see, the block elements are inconsistent. I thought that each of these special nodes were independent. I'm not sure if this has been reported before, but I don't know how to proceed after much trial and error.

Any help is greatly appreciated, thank you!

Edit: [here is a gist](https://gist.githubusercontent.com/kamodulin/0a891b73aadc3e623c9a87e4ab56f446/raw/3d1d7cde28ccbafed80bb7000dfcaa7225d4e882/st-datocms-issue.json) of the raw structured text data.

**Comment by stefanoverna** [comment]
Hi, thanks for the deets. This is what I get, which seems correct AFAIKT:

![Screenshot 2022-03-25 at 14 46 03](https://user-images.githubusercontent.com/51573/160132730-8a3b1e07-8bfd-4e31-a3d5-240f71b2ab36.png)

Not sure how you're getting that incorrect result 😕

**Comment by stefanoverna** [comment]
Feel free to reopen the ticket if you've time to give us some more information!
