### ISSUE TITLE
Setting a max-width on an Image component sets inline styles

### ISSUE THREAD

**Issue by buzzguy** [datocms/react-datocms#57]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1154836/173880103-a06da6b3-24aa-4abd-b5fb-b464ed808cef.png">

if a max-width is set on the image component, it does something funky in mobile view

**Comment by stefanoverna** [comment]
Hi, could you please provide a reproducible example with the issue?

You can fork this codesandbox if it's easier for you: https://codesandbox.io/s/lucid-surf-thc67b

Thanks!
