### ISSUE TITLE
[feature request] add fetchpriority prop for image

### ISSUE THREAD

**Issue by kelenakamura** [datocms/react-datocms#58]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority

like next/image - https://nextjs.org/docs/api-reference/next/image#priority

**Comment by dbismut** [comment]
I came here for the same reason but it looks like the feature isn't widely supported yet thought.

**Comment by timvandevelde** [comment]
+1

**Comment by stefanoverna** [comment]
Added in v4! https://github.com/datocms/react-datocms/releases/tag/v4.0.0
