### ISSUE TITLE
Render fragment changed behavior

### ISSUE THREAD

**Issue by kiily** [datocms/react-datocms#59]
Hi there,

We were trying to upgrade `react-datocms` to the latest version (currently in 1.6.3) and it seems to break the current setup we have for rendering components. We only used the `StructuredText` component so the issue is confined to that.

Specifically, the `renderFragment` function is returning a modified set of `children` which now include plain strings in arrays (whereas before everything was an object)

e.g. `["Some text content here"]` now vs. before:

```
0:
$$typeof: Symbol(react.element)
key: "t-0"
props: {children: Array(1)}
ref: null
type: "p"
_owner: FiberNode {tag: 0, key: null, stateNode: null, elementType: ƒ, type: ƒ, …}
_store: {validated: false}
_self: null
_source: null
[[Prototype]]: Object
```

We were relying on the fact that we were only receiving objects in the `children` arrays that we get from the component but as soon as we upgrade the strings that come through cause things to break.

Is this behavior expected and if so could you point us somewhere that would help us debug the problem? How should we be using `renderFragment` with this new setup?

Thank you in advance. Happy to provide more info if required 🙏

**Comment by stefanoverna** [comment]
Hey! Could you please share the code that was relying on this constraint, so we can take a look at it? Thanks!
