### ISSUE TITLE
Progressive image doesn't work on browsers without IntersectionObserver API

### ISSUE THREAD

**Issue by pauloborges** [datocms/react-datocms#6]
To verify you can visit https://react-datocms-example.netlify.com/ on an iPhone with iOS/Safari version 12. If you don't have such device you can use something like [browserstack.com](https://www.browserstack.com/).

It breaks due to some browsers not having the [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). The dependency on this API isn't stated anywhere in the README.

According to caniuse.com almost 7% of tracked user agents don't support it. Since this is somewhat a big fraction of users, it would be really good if this library could verify if the API is available before using it. Having to include a polyfill shouldn't be required.

**Comment by matjack1** [comment]
Thank you @pauloborges. Your observation makes total sense, we'll investigate as soon as possible!

**Comment by stefanoverna** [comment]
@pauloborges v1.2.2 should now work, could you please try it and report back? 😄
