### ISSUE TITLE
GraphQL and StructuredText Types incompatible

### ISSUE THREAD

**Issue by moshie** [datocms/react-datocms#60]
## Problem

`blocks` and `links` are typed as `[String!]!` in GraphQL and this type is incompatible with the Record type defined in the structured Text component.

<img width="406" alt="Screenshot 2022-08-24 at 14 00 21" src="https://user-images.githubusercontent.com/3974301/186424889-d20b67fa-56e4-4c6f-9fb8-11c7c2cffdce.png">

This is a problem when using a [code generator](https://www.graphql-code-generator.com/plugins/typescript/typescript) to auto generate the types.

```
Type '{ __typename: "TestBlockModelContentField"; value: Document; blocks: string[]; links: string[]; } | null | undefined' is not assignable to type 'Document | Node | StructuredText<Record, Record> | null | undefined'.
  Type '{ __typename: "TestBlockModelContentField"; value: Document; blocks: string[]; links: string[]; }' is not assignable to type 'Document | Node | StructuredText<Record, Record> | null | undefined'.
    Type '{ __typename: "TestBlockModelContentField"; value: Document; blocks: string[]; links: string[]; }' is not assignable to type 'StructuredText<Record, Record>'.
      Types of property 'blocks' are incompatible.
        Type 'string[]' is not assignable to type 'Record[]'.
          Type 'string' is not assignable to type 'Record'.
            Type 'string' is not assignable to type '{ __typename: string; id: string; }'.ts(2322)
index.d.ts(30, 5): The expected type comes from property 'data' which is declared here on type 'IntrinsicAttributes & StructuredTextPropTypes<Record, Record>'
````

I would like to avoid casting or forcing this type to be something else. Ideally the graphQL type needs to be updated or the structured text package.

Similar to this issue: https://github.com/datocms/react-datocms/issues/33

**Comment by stefanoverna** [comment]
The `[String!]!` type happens only when a particular structured text field is configured to have NO possible links/blocks. In this case `blocks` and `links` can only be an empty array, but with GraphQL we need to specify a type for the empty array.

I suggest you to remove `blocks` and `links` from the GraphQL query on structured text fields that cannot have any link/block. 

Does it make any sense? I'm gonna close this for now, but feel free to reopen!
