### ISSUE TITLE
Export ImagePropTypes type

### ISSUE THREAD

**Issue by illarionvk** [datocms/react-datocms#65]
We have a custom wrapper component that uses the `Image` component if the image is a responsive Imgix image and uses a different component if it's an SVG file.

It would be convenient if I could import and use the ImagePropTypes type in my component's props.

https://github.com/datocms/react-datocms/blob/202e04b0ae752c29309ca46e4bba25a906021dbf/src/Image/index.tsx#L38

**Comment by stefanoverna** [comment]
Version 3.1.4 exports `ImagePropTypes`! 👍🏼
