### ISSUE TITLE
Seeing duplicate key errors in StructuredText component

### ISSUE THREAD

**Issue by cwrichardson** [datocms/react-datocms#68]
Not sure if anyone else is seeing this, but sometime (I think very recently) I've started getting "Encountered two children with the same key, `t-0`" warnings in my dev environment.

For the life of me, I don't think this was there a month ago, which was the last time we shipped to production, but I've gone through my entire git history until long before that, and I keep getting the error. My suspicion is that one of the API changes is interacting poorly with the component, but ... I wanted to check if anyone else was seeing it.

So far, we've been on version 3.1.2, but in trying to debug this updated to 4.0.6, and that didn't resolve the issue.

FWIW, the full error is

```
next-dev.js?3515:20 Warning: Encountered two children with the same key, `t-0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at StructuredText (webpack-internal:///./node_modules/react-datocms/dist/esm/StructuredText/index.js:42:19)
    at div
    at DatoContent (webpack-internal:///./components/DatoContent.js:40:25)
    at div
    at GridColumn (webpack-internal:///./components/GridColumn.js:12:25)
    at section
    at Section (webpack-internal:///./components/Section.js:17:34)
    at div
    at PageLandingPage (webpack-internal:///./components/PageLandingPage.js:24:22)
    at Page (webpack-internal:///./pages/[page].js:20:22)
    at HeaderProvider (webpack-internal:///./utils/context/header.js:24:26)
    at MyApp (webpack-internal:///./pages/_app.js:15:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23632)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:71:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:592:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:703:27)
```

And if I look at it in Chrome DevTools there are only three places where the page goes `PageLandingPage > Section > GridColumn > DatoContent > StructuredText`, and I can't visually see any duplicated keys here:

```
PageLandingPage
...
  Section key="39835727"
    GridColumn key="0"
      DatoContent
        StructuredText
          RuleOfThree key="t-3"
...
  Section key="36771397"
    GridColumn key="0"
      DatoContent
        StructuredText
          Quadrant key="t-2"
...
  Section key="32158676"
    GridColumn key="0"
      DatoContent
        StructuredText
          Testimonials key="t-0"
...
```

And finally, in case no one else is seeing this and it's actually some bonehead move on my part, if the line numbers are to be believed, here's the relevant section of my code for my `<DatoContent>` component:

```
const DatoContent = ({ content, filters=[] }) => {
    const nodeRules = [
        renderNodeRule(isList,
            ({ adapter: { renderNode }, node, children, key }) => {
                if ( 'bulleted' === node.style && (filters.includes('checklist') || filters.includes('productCard')) ) {
                    let classes = 'list-["✓"] pl-4 ml-4';
                    if (filters.includes('featured')) classes += ' text-accent-800 dark:text-accent-200';

                    return renderNode(
                        'ul',
                        { key, className: classes },
                        children,
                    );
                } else if ( 'bulleted' === node.style ) {
                    return renderNode(
                        'ul',
                        { key },
                        children,
                    );
                } else {
                    return renderNode(
                        'ol',
                        { key },
                        children,
                    ); // line 40
                }
            }
        )
    ]
```

**Comment by stefanoverna** [comment]
Could you also provide us a sample of a structured text value that reproduces the issue?

**Comment by stefanoverna** [comment]
Just tried... cannot see any error in the console.. :/ 

https://codesandbox.io/s/structured-text-sample-27e1m0

Maybe you can tweak the sandbox code until you can reproduce the issue?

**Comment by cwrichardson** [comment]
Sorry, it took me a while to get to this. Broken version here:

https://codesandbox.io/s/structured-text-sample-broken-x7r8c3

**Comment by stefanoverna** [comment]
Thanks @cwrichardson! This should solve the issue I think:

```
if (node.children.find(({ type }) => type === "inlineItem")) {
  return <React.Fragment key={key}>{children}</React.Fragment>;
} else {
  return renderNode("p", { key, children });
}
```

**Comment by cwrichardson** [comment]
Super cool. Thanks @stefanoverna, that solves the issue. But you guys should probably update the docs, as that code snippet is taken directly from them:

https://github.com/datocms/react-datocms/blob/master/docs/structured-text.md#override-default-rendering-of-nodes

> In this case, you can easily override default rendering rules with the customNodeRules and customMarkRules props.
> ```
> <StructuredText
>   ...
>. // Apply different formatting to top-level paragraphs
>    renderNodeRule(
>      isParagraph,
>     ({ adapter: { renderNode }, node, children, key, ancestors }) => {
>       // Proceed with default paragraph rendering...
>       // return renderNode('p', { key }, children);
>
>       // Or even completely remove the paragraph and directly render the inner children:
>        return children;
>```
