### ISSUE TITLE
[feature request] Subscript & Subscript Tags

### ISSUE THREAD

**Issue by moshie** [datocms/react-datocms#71]
Do you have plans to implement these missing tags into structured text? `<sup>`, `<sub>`

We have some text that has a registered trademark `®` also I see this would be useful for dates i.e `22<sup>nd</sup>`

We can replace it in a `renderNodeRule` but this isn't a clean solution.

**Comment by sistrall** [comment]
Hi @moshie,

If I get right what you're asking, I'm happy to share that we have an open feature request on the topic: would you mind [upvoting it](https://community.datocms.com/t/subscript-superscript-in-structured-text/1762)?

**Comment by matjack1** [comment]
Since the feature is tracked there already I'm closing this to avoid duplication
