### ISSUE TITLE
Image placeholder doesn't take transparencies into account

### ISSUE THREAD

**Issue by pabsan-iron** [datocms/react-datocms#73]
When using an image that has some transparency, this isn't taken into account when generating the base64 version for the placeholder, resulting in square images with coloured backgrounds.

<img width="302" alt="Screenshot 2023-01-16 at 14 12 26" src="https://user-images.githubusercontent.com/120574596/212686516-115ebcbc-a5e5-4930-9224-50db089c7fb7.png">

It would be great to have transparencies taken into account to provide more options when handling all kinds of images.

The desired result would be something similar to what this user has done with next/image:
https://gabrielm-linassi.medium.com/how-to-incrementally-load-transparent-images-with-nextjs-28ca5fdc8d6b

**Comment by stefanoverna** [comment]
Fixed! https://www.datocms.com/blog/introducing-thumbhash-the-compact-placeholder-with-alpha-support
