### ISSUE TITLE
NextJS 13 App Dir StructuredText

### ISSUE THREAD

**Issue by SamKomesarook** [datocms/react-datocms#78]
Hello! I am using the `StructuredText` component to render a text block in the new Next13 App Dir, however I am getting the following error when I try to build it:

`TypeError: Cannot read properties of undefined (reading 'prototype')`

I am fetching the data via gql and have confirmed that the build succeeds, and the data is fetched correctly when the `StructuredText` component isn't present.

**Comment by hundehausen** [comment]
I get the same error

**Comment by david-kiwibio** [comment]
Getting the same error too

**Comment by stefanoverna** [comment]
Hey guys, can someone share a small repo reproducing the issue please?

**Comment by stefanoverna** [comment]
I've recently used Next 13 and the `app` dir together with Structured Text, and I had no issues.. https://github.com/stefanoverna/taiza-rossini/blob/main/app/about/page.tsx#L71-L73

**Comment by SamKomesarook** [comment]
@stefanoverna [here](https://github.com/Kiwi-Biosciences/dato-test) is one. I will note your example is using Next 13.2.1, and we require 13.3.1.

**Comment by stefanoverna** [comment]
Alright, v4.0.13 should fix the issue! Thank you for your help @SamKomesarook!
