### ISSUE TITLE
Image `fetchPriority` throwing errors

### ISSUE THREAD

**Issue by fcisio** [datocms/react-datocms#79]
Hi, I noticed some new errors after `fetchPriority` was added to the Image component.

> warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

From my research, I believe that the camel case `fetchPriority` is reserved for JS, while the lowercase `fetchpriority` can be used as an HTML Img attribute - [see reference](https://web.dev/fetch-priority/#the-fetchpriority-attribute).

---

So a simple change of case should fix the issue,
Thanks.

**Comment by cwrichardson** [comment]
Concur. This warning doesn't happen in 4.0.10, but does in 4.0.11 onwards through current.

**Comment by stefanoverna** [comment]
It's funny. Newer versions of React throw the same error when passing `fetchpriority` instead of the camel cased variant :)

**Comment by lobosan** [comment]
same issue for me, please help us fixing this warning

**Comment by stefanoverna** [comment]
Fixed in 4.0.15!
