### ISSUE TITLE
Type mismatch between useSiteSearch<GenericClient> and cma-client

### ISSUE THREAD

**Issue by marcosmesser** [datocms/react-datocms#80]
Trying to use the hook from [docs](https://www.datocms.com/docs/site-search/widget), I am unable to compile.

> Type error: Type 'Client' is not assignable to type 'GenericClient'.
The types of 'searchResults.rawList' are incompatible between these types.
Type '(queryParams: import("@datocms/cma-client/dist/types/generated/SchemaTypes").SearchResultInstancesHrefSchema) => Promise<...>' is not assignable to type '(queryParams: SearchResultInstancesHrefSchema) => Promise<SearchResultInstancesTargetSchema>'.
Types of parameters 'queryParams' and 'queryParams' are incompatible.
 Type 'SearchResultInstancesHrefSchema' is not assignable to type 'import("@datocms/cma-client/dist/types/generated/SchemaTypes").SearchResultInstancesHrefSchema'.
 The types of 'filter.fuzzy' are incompatible between these types.
 Type 'string' is not assignable to type 'boolean'.

- @datocms/cma-client-browser 1.3.2
- react-datocms 4.0.13

**Comment by stefanoverna** [comment]
Fixed in react-datocms@4.0.14!
