### ISSUE TITLE
Update to latest version of datocms-listen

### ISSUE THREAD

**Issue by JanStevens** [datocms/react-datocms#81]
Hi,

Can this package update to latest version of datocms-listen? I would like to try out the TypedDocumentNode option but with current version this is not yet supported 😅 

Regards

**Comment by JanStevens** [comment]
The package lock file specifies 1.0.14 so I think that version is used. Probably if I add the package explicit it will take the latest version 🤔

**Comment by stefanoverna** [comment]
An `npm upgrade` should fix the issue, please reopen this if you're having problems :)
