### ISSUE TITLE
[feature request]: Support Next.js 13 Metadata object

### ISSUE THREAD

**Issue by palmamartin** [datocms/react-datocms#82]
Now that the app directory is stable in Next.js 13. it would be great if this library would support or provide an helper function to transform a GraphQL `_seoMetaTags` object in a Next Metadata object.

**Comment by sistrall** [comment]
Hi @palmamartin,

I released an update of `react-datocms` that makes a new helper available: `toNextMetadata()` returns a Next `Metadata` object. It's shortly documented [here](https://github.com/datocms/react-datocms/blob/master/docs/meta-tags.md#tonextmetadata): any feedback is welcome. :-)

**Comment by sistrall** [comment]
Hello @inakianduaga,

could you tell me which version of Next you're currently using?

I noticed that errors are far more clear starting from version 13.4.5 and I solved a similar import issue by upgrading Next.
