### ISSUE TITLE
[feature request]: Support for Next.js app directory

### ISSUE THREAD

**Issue by bramvdpluijm** [datocms/react-datocms#83]
Hi there! First of all I've been using Dato as my go-to CMS for a while now and it doesn't look like that's gonna change very soon either. You guys are doing a great job!

Now that Next.js app directory has been stable for a while: can you say anything yet about when react-datocms will support it? The `<Image />` component doesn't seem to handle the latest version of Next.js well yet because it throws errors. I assume it has to do with app directory.  

Upon usage it throws: 
`Error: (0 , react_1.useState) is not a function`

**Comment by bramvdpluijm** [comment]
Hi there! I think this issue can be closed. I didn't notice the error was thrown because I tried to use the <Image /> component in a server component, where it should've been a client component. Sorry for the inconvenience :)

**Comment by stefanoverna** [comment]
Thanks @bramvdpluijm! We might wanna mark the Image component as a client component though, right? So that everything works also if the Image component is used in a server side component.

**Comment by bramvdpluijm** [comment]
Yeah, that might be a good improvement! :)

**Comment by sistrall** [comment]
@bramvdpluijm I'm on it. :-)

**Comment by sistrall** [comment]
@everettglovier could you please try version `^13.4.5`? I noticed that errors are far more clear on 13.4.5, and I managed to solve an `Unsupported Server Component type: undefined` just by updating and fixing some minor stuff.

**Comment by jpwallace22** [comment]
I am now forced to render the entire structured text parser on the client side for some reason. Even when not using the `Image` component. This didnt happen till I upgraded to from 13.4.4 to 13.4.6.
