### ISSUE TITLE
Getting odd unicode encoding in my resulting page 

### ISSUE THREAD

**Issue by PandelisZ** [datocms/react-datocms#86]
![image](https://github.com/datocms/react-datocms/assets/8436717/03aba0e0-3c78-4bc0-9552-465dd6315898)

Using the astro dato example

Edit: I think it could be perhaps a bug with firefox and the dato link auto-encoded when pasting in formatted text in the editor. I'm manually in the editor going to the links, backpsacing and entering space again and that seems to fix it

edit2: doing more cleanup, it does seem to be more editor related than anything else, i get badly encoded quotations too 
![Screenshot 2023-09-04 002643](https://github.com/datocms/react-datocms/assets/8436717/6c2a01af-d164-4ebb-b342-4b783e2d2724)

the classic "pasted from word"type quotes

had to use https://textcleaner.net/

**Comment by marcelofinamorvieira** [comment]
Hello @PandelisZ 

Can you email us at support@datocms.com with a record URL example that has a structured text that is returning these strange chars? This way we can reproduce it exactly as you are experiencing it as check what could be going on on our end. Thank you!
