### ISSUE TITLE
Next14 react-datocms@4.2.0 build error

### ISSUE THREAD

**Issue by Lorezz** [datocms/react-datocms#93]
Hi i get this error when i try to build my next.js project, even if I'm not using Videoplayer anywhere.
 
`./node_modules/@mux/playback-core/dist/index.mjs
Attempted import error: 'hls.js' does not contain a default export (imported as 'ye').`

To reproduce: 
use `bun` as  package installer, 
install next.js@latest, react-datocms@4.2.0, @mux/mux-player-react
run `bun run build`

Thanks.

**Comment by sistrall** [comment]
@Lorezz thanks for reporting this.

I tried to reproduce the issue locally, but I've had no luck (it must be said that I'm not a Bun expert, so YMMV).

In the meantime, this afternoon, I released version [4.2.1](https://github.com/datocms/react-datocms/releases/tag/v4.2.1) that declares @mux/mux-player-react as an **optional** peer dependency: maybe that gives a good hint during the build?
