### ISSUE TITLE
Could not resolve "@mux/mux-player-react/lazy"

### ISSUE THREAD

**Issue by wouterds** [datocms/react-datocms#94]
Just updated `react-datocms` using @dependabot but ended up reverting as my build pipeline seems to fail with:

**`Could not resolve "@mux/mux-player-react/lazy"`**.

![Screenshot 2024-03-11 at 14 07 12](https://github.com/datocms/react-datocms/assets/1210628/31a64fcf-1698-4234-ad0c-1aba7fe35d95)

I don't think it's right to have `@mux/mux-player-react` as an optional peer dependency if it's required for this package to work. Probably it should even be just a direct dependency in that case.

**Comment by wouterds** [comment]
I just saw this open issue https://github.com/datocms/react-datocms/issues/93, for the record, I'm also not using any video content / features right now.

**Comment by sistrall** [comment]
Hi @wouterds!

Could you give some context? Are you using `react-datocms` in a pure React application or are you using Next or some other framework?

**Comment by bnachtweh** [comment]
@sistrall I also encounter this issue after updating to 4.2.1. 

I'm using react-datocms in combination with Next.js (14.1.3) 

See: https://codesandbox.io/p/github/bnachtweh/empty-next-app

**Comment by sistrall** [comment]
@bnachtweh @wouterds I just released version 4.2.2 that makes the MUX player a `@mux/mux-player-react`: it seems indeed to be the safest approach.

Please let me know if this fixes your the issue.

**Comment by bnachtweh** [comment]
@sistrall that seems to have fixed the issue for me, thanks! 👌🏻

**Comment by wouterds** [comment]
Seems to be resolved, thanks!
